CREATE DATABASE IF NOT exists STUDENT;
#CREATE DATABASE STUDENT2;

# DROP DATABASE STUDENT3;

USE STUDENT;
DROP TABLE IF EXISTS STUDENT.STUDENT;
CREATE TABLE IF NOT EXISTS STUDENT.STUDENT(
	ST_KEY INT PRIMARY KEY AUTO_INCREMENT,
    ST_GRADE INT NOT NULL DEFAULT 1,
    ST_CLASS INT NOT NULL DEFAULT 1,
    ST_NUM INT NOT NULL DEFAULT 1,
    ST_NAME VARCHAR(20) NOT NULL,
    CHECK(ST_GRADE >= 1),
    CHECK(ST_CLASS >= 1),
    CHECK(ST_NUM >= 1)
);

# DROP TABLE STUDENT;
ALTER TABLE STUDENT ADD ST_TEST DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE STUDENT CHANGE ST_TEST TEST CHAR(3) NOT NULL;

ALTER TABLE STUDENT DROP TEST;

SELECT * FROM INFORMATION_SCHEMA.CHECK_CONSTRAINTS;

ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_CHK4 CHECK(ST_NAME != '');

ALTER TABLE STUDENT DROP CONSTRAINT STUDENT_CHK4;

INSERT INTO STUDENT.STUDENT(ST_GRADE, ST_CLASS, ST_NUM, ST_NAME)
VALUES(1,1,1, "홍길동"), (1,1,2,"임꺽정");

SELECT * FROM STUDENT.STUDENT;

INSERT INTO STUDENT.STUDENT(ST_GRADE, ST_CLASS, ST_NUM, ST_NAME)
VALUES(1,1,1, "홍길동"), (1,1,2,"임꺽정");

SELECT * FROM STUDENT.STUDENT;

TRUNCATE TABLE STUDENT.STUDENT;

INSERT INTO STUDENT.STUDENT(ST_GRADE, ST_CLASS, ST_NUM, ST_NAME)
VALUES(1,1,3, "홍길동"), (1,1,4,"임꺽정");

SELECT * FROM STUDENT.STUDENT;

DROP TABLE IF EXISTS STUDENT.SUBJECT;

CREATE TABLE STUDENT.SUBJECT(
	SJ_NUM INT PRIMARY KEY AUTO_INCREMENT,
    SJ_GRADE INT NOT NULL DEFAULT 1,
    SJ_SEMESTER ENUM("1", "2") NOT NULL DEFAULT "1",
    SJ_NAME VARCHAR(10) NOT NULL,
    CHECK(SJ_GRADE IN (1,2,3))
);

DROP TABLE IF EXISTS STUDENT.SCORE;

CREATE TABLE STUDENT.SCORE(
	SC_NUM INT PRIMARY KEY AUTO_INCREMENT,
    SC_ST_KEY INT NOT NULL,
    SC_SJ_NUM INT NOT NULL,
    SC_SCORE INT NOT NULL DEFAULT 0,
    CHECK(SC_SCORE BETWEEN 0 AND 100),
    FOREIGN KEY(SC_ST_KEY) REFERENCES STUDENT.STUDENT(ST_KEY),
    FOREIGN KEY(SC_SJ_NUM) REFERENCES STUDENT.SUBJECT(SJ_NUM)
);


DROP TABLE IF EXISTS STUDENT.AVERAGE;

CREATE TABLE STUDENT.AVERAGE(
	AV_NUM INT PRIMARY KEY AUTO_INCREMENT, 
    AV_ST_KEY INT NOT NULL,
    AV_GRADE INT NOT NULL,
    AV_SEMESTER INT NOT NULL,
    AV_SUM INT NOT NULL,
    AV_COUNT INT NOT NULL,
    FOREIGN KEY(AV_ST_KEY) REFERENCES STUDENT.STUDENT(ST_KEY)
);

ALTER TABLE `student`.`score` DROP FOREIGN KEY `score_ibfk_1`;
ALTER TABLE `student`.`score` ADD CONSTRAINT `score_ibfk_1`
  FOREIGN KEY (`SC_ST_KEY`)  REFERENCES `student`.`student` (`ST_KEY`)  ON DELETE CASCADE;


ALTER TABLE `student`.`score` DROP FOREIGN KEY `score_ibfk_2`;
ALTER TABLE `student`.`score` ADD CONSTRAINT `score_ibfk_2`
  FOREIGN KEY (`SC_SJ_NUM`)  REFERENCES `student`.`subject` (`SJ_NUM`)  ON DELETE CASCADE;


ALTER TABLE `student`.`average` DROP FOREIGN KEY `average_ibfk_1`;
ALTER TABLE `student`.`average` ADD CONSTRAINT `average_ibfk_1`
  FOREIGN KEY (`AV_ST_KEY`)  REFERENCES `student`.`student` (`ST_KEY`)  ON DELETE CASCADE;



