

#ROW_NUMBER() OVER
USE WINDOW_FUNC;
SELECT ROW_NUMBER() OVER(ORDER BY TS_SCORE DESC) AS 순위, TEAM_SCORE.* FROM TEAM_SCORE;

SELECT RANK() OVER(ORDER BY TS_SCORE DESC) AS 순위, TEAM_SCORE.* FROM TEAM_SCORE;

SELECT DENSE_RANK() OVER(ORDER BY TS_SCORE DESC) AS 순위, TEAM_SCORE.* FROM TEAM_SCORE;

SELECT NTILE(2) OVER(ORDER BY TS_SCORE DESC) AS 순위, TEAM_SCORE.* FROM TEAM_SCORE;