DROP DATABASE IF EXISTS Cafe;
CREATE DATABASE Cafe;
USE CAFE;

DROP TABLE IF EXISTS `MENU`;


CREATE TABLE `MENU` (
	`ME_CODE`	CHAR(6) PRIMARY KEY NOT NULL,
	`ME_CA_NUM`	INT	NOT NULL,
	`ME_NAME`	VARCHAR(20)  NOT	NULL,
	`ME_PRICE`	INT DEFAULT 0 NOT	NULL,
	`ME_CONTENT`	LONGTEXT NOT	NULL,
	`ME_THUMB`	VARCHAR(200)	NULL,
	`ME_ABLE`	ENUM('Y', 'N') DEFAULT "Y" NOT	NULL,
	`ME_HOT_ICE`	ENUM("H","I") DEFAULT "I" NOT	NULL
);

DROP TABLE IF EXISTS `COUPON`;

CREATE TABLE `COUPON` (
	`CO_KEY`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`CO_M_ID`	VARCHAR(13) UNIQUE NOT NULL,
	`CO_COUNT`	INT DEFAULT 0 NOT	NULL
);

DROP TABLE IF EXISTS `Menu_Tag`;

CREATE TABLE `Menu_Tag` (
	`MT_NUM`	INT	NOT NULL,
	`MT_TAG_NUM`	INT	NOT NULL,
	`MT_ME_CODE`	CHAR(6)	NOT NULL
);

DROP TABLE IF EXISTS `CATEGORY`;

CREATE TABLE `CATEGORY` (
	`CA_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`CA_NAME`	VARCHAR(10) UNIQUE NOT	NULL,
	`CA_CODE`	CHAR(3) NOT	NULL
);

DROP TABLE IF EXISTS `Member`;

CREATE TABLE `Member` (
	`M_ID`	VARCHAR(13) PRIMARY KEY	NOT NULL,
	`M_PW`	VARCHAR(20) NOT	NULL,
	`M_NUMBER`	VARCHAR(13) UNIQUE NOT	NULL,
	`M_NICKNAME`	VARCHAR(10) NOT	NULL,
	`M_AUTHORITY`	ENUM("ADMIN","CUSTOMER") DEFAULT "CUSTOMER" NOT	NULL,
	`M_DEL`	ENUM("Y","N") DEFAULT "N" NOT	NULL,
	`M_DEL_TIME`	DATETIME DEFAULT NULL	NULL
);

DROP TABLE IF EXISTS `INCOME`;

CREATE TABLE `INCOME` (
	`IN_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`IN_DATE`	DATETIME DEFAULT CURRENT_TIMESTAMP NOT	NULL,
	`IN_MONEY`	INT DEFAULT 0 NOT	NULL
);

DROP TABLE IF EXISTS `CART_LIST`;

CREATE TABLE `CART_LIST` (
	`CL_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`CL_ME_CODE`	CHAR(6)	NOT NULL,
	`CL_CT_NUM`	INT	NOT NULL,
	`CL_AMOUNT`	INT DEFAULT 0 NOT	NULL
);

DROP TABLE IF EXISTS `TAG`;

CREATE TABLE `TAG` (
	`TAG_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`TAG_NAME`	VARCHAR(30) UNIQUE NOT	NULL
);

DROP TABLE IF EXISTS `ORDER`;

CREATE TABLE `ORDER` (
	`OR_NUM`	INT  PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`OR_CT_NUM`	INT	NOT NULL,
	`OR_M_ID`	VARCHAR(13)	NOT NULL,
	`OR_USE`	INT DEFAULT 0 NOT	NULL,
	`OR_TOTAL`	INT DEFAULT 0 NOT	NULL,
	`OR_DATE`	DATETIME DEFAULT CURRENT_TIMESTAMP NOT	NULL,
	`OR_FINAL`	INT DEFAULT 0 NOT	NULL
);

DROP TABLE IF EXISTS `STAMP`;

CREATE TABLE `STAMP` (
	`ST_KEY`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`ST_M_ID`	VARCHAR(13)  UNIQUE NOT NULL,
	`ST_COUNT`	INT DEFAULT 0 NOT	NULL
);

DROP TABLE IF EXISTS `CART`;

CREATE TABLE `CART` (
	`CT_NUM`	INT  PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`CT_M_ID`	VARCHAR(13)	NOT NULL,
	`CT_PRICE`	INT DEFAULT 0 NOT	NULL,
	`CT_STATUS`	ENUM("Y","N") DEFAULT "N" NOT	NULL
);


ALTER TABLE `MENU` ADD CONSTRAINT `FK_CATEGORY_TO_MENU_1` FOREIGN KEY (
	`ME_CA_NUM`
)
REFERENCES `CATEGORY` (
	`CA_NUM`
);

ALTER TABLE `COUPON` ADD CONSTRAINT `FK_Member_TO_COUPON_1` FOREIGN KEY (
	`CO_M_ID`
)
REFERENCES `Member` (
	`M_ID`
);

ALTER TABLE `Menu_Tag` ADD CONSTRAINT `FK_TAG_TO_Menu_Tag_1` FOREIGN KEY (
	`MT_TAG_NUM`
)
REFERENCES `TAG` (
	`TAG_NUM`
);

ALTER TABLE `Menu_Tag` ADD CONSTRAINT `FK_MENU_TO_Menu_Tag_1` FOREIGN KEY (
	`MT_ME_CODE`
)
REFERENCES `MENU` (
	`ME_CODE`
);

ALTER TABLE `CART_LIST` ADD CONSTRAINT `FK_MENU_TO_CART_LIST_1` FOREIGN KEY (
	`CL_ME_CODE`
)
REFERENCES `MENU` (
	`ME_CODE`
);

ALTER TABLE `CART_LIST` ADD CONSTRAINT `FK_CART_TO_CART_LIST_1` FOREIGN KEY (
	`CL_CT_NUM`
)
REFERENCES `CART` (
	`CT_NUM`
);

ALTER TABLE `ORDER` ADD CONSTRAINT `FK_CART_TO_ORDER_1` FOREIGN KEY (
	`OR_CT_NUM`
)
REFERENCES `CART` (
	`CT_NUM`
);

ALTER TABLE `ORDER` ADD CONSTRAINT `FK_Member_TO_ORDER_1` FOREIGN KEY (
	`OR_M_ID`
)
REFERENCES `Member` (
	`M_ID`
);

ALTER TABLE `STAMP` ADD CONSTRAINT `FK_Member_TO_STAMP_1` FOREIGN KEY (
	`ST_M_ID`
)
REFERENCES `Member` (
	`M_ID`
);

ALTER TABLE `CART` ADD CONSTRAINT `FK_Member_TO_CART_1` FOREIGN KEY (
	`CT_M_ID`
)
REFERENCES `Member` (
	`M_ID`
);

SELECT 
    M.ME_CODE,  -- 메뉴 코드
    M.ME_NAME,  -- 메뉴 이름
    M.ME_PRICE, -- 가격
    CL.CL_AMOUNT -- 수량
FROM CART C
JOIN CART_LIST CL ON C.CT_NUM = CL.CT_NUM
JOIN MENU M ON CL.CL_ME_CODE = M.ME_CODE
WHERE C.CT_NUM = 1;  -- 특정 장바구니 번호